#!/usr/bin/env python3
# 
# BELERIAND (Sindarin full mode)
#
# This file defines all different sets of variables that are used within the language of Quenya
# From vowels to consonants and clusters, and conversion dictionaries


# ------- VOWELS -------
non_accent = {"a", "e", "i", "o", "u"}
accent = {"á", "é", "í", "ó", "ú"}

vowels = non_accent | accent

# ------- Clusters -------

consonant_clusters = {"th", "ph", "ch", "dh", "nn", "mm", "rh", "lh", "ss", "ll", "rr", "hw", "nt", "nd", "mp", "mb", "nk", "ng"}
diphtongs = {"ae", "oe", "ai", "ei", "ui", "au", "aw"}

clusters = consonant_clusters | diphtongs

cluster_dict = {
    "th" : "T",
    "ph" : "f",
    "ch" : "C",
    "dh" : "D",
    "nn" : "N",
    "mm" : "M",
    "rh" : "ŕ",
    "lh" : "ĺ",
    "ss" : "S",
    "ll" : "L",
    "rr" : "R",
    "hw" : "W",
    "nt" : "ń",
    "nd" : "ǹ",
    "mp" : "ḿ",
    "mb" : "B",
    "nk" : "ć",
    "ng" : "ǵ",
    "ae" : "Á",
    "oe" : "Ó",
    "ai" : "À",
    "ei" : "È",
    "ui" : "Ù",
    "au" : "Ú",
    "aw" : "Ú"
}

# ------- NUMBERS -------
numbers = {"0", "1", "2", "3", "4", "5", "6", "7", "8", "9"}
numbers_to_duodec = {
    "0" : "Z",
    "1" : "µ",
    "2" : "ẗ",
    "3" : "ĸ",
    "4" : "ð",
    "5" : "$",
    "6" : "ſ",
    "7" : "ŧ",
    "8" : "ø",
    "9" : "æ",
    "§" : "§",
    "þ" : "þ"
}
# ------- CHARACTER CONVERSION -------
letters_dict = {
    "th" : "T" : "\\Tthuule",
    "ch" : "C" : "\\Taha",
    "dh" : "D" : "\\Tanto",
    "nn" : "N" : "\\Tnuumen",
    "mm" : "M" : "\\Tmalta",
    "rh" : "ŕ" : "\\Tarda",
    "lh" : "ĺ" : "\\Talda",
    "ss" : "S" : "\\Tesse",
    "ll" : "L" : "\\Tlambe\\Tlambe",
    "rr" : "R" : "\\Troomen\\Troomen",
    "hw" : "W" : "\\Thwestasindarinwa",
    "nt" : "ń" : "\\Ttinco\\TTnasalizer",
    "nd" : "ǹ" : "\\Tando\\TTnasalizer",
    "mp" : "ḿ" : "\\Tparma\\TTnasalizer",
    "mb" : "B" : "\\Tumbar\\TTnasalizer",
    "nk" : "ć" : "\\Tcalma\\TTnasalizer",
    "ng" : "ǵ" : "\\Tanga\\TTnasalizer",
    "ae" : "Á" : "\\Tosse\\hspace{-5pt}{\\raisebox{+1.5ex}{\\rotatebox[origin=c]{180}{\\TTcaron}}}\\hspace{5pt}",
    "oe" : "Ó" : "\Tanna\hspace{-6.5pt}{\raisebox{+1.5ex}{\rotatebox[origin=c]{180}{\TTcaron}}}\hspace{6.5pt}",
    "ai" : "À" : "\\Tosse\\TTtwodots",
    "ei" : "È" : "\\Tyanta\\TTtwodots",
    "ui" : "Ù" : "\\Tuure\\TTtwodots",
    "au" : "Ú" : "\\Tosse\\TTtilde",


    "t" : "\\Ttinco",
    "p" : "\\Tparma",
    "c" : "\\Tcalma",
    "k" : "\\Tcalma",
    "f" : "\\Tformen",
    "n" : "\\Tnuumen",
    "m" : "\\Tmalta",
    "r" : "\\Troomen",
    "@" : "\\Toore",
    "v" : "\\Tvala",
    "w" : "\\Tvilya",
    "y" : "\\Tanna\\TTtwodotsbelow",
    "l" : "\\Tlambe",
    "s" : "\\Tsilme",
    "ś" : "\\Tsilmenuquerna",
    "x" : "\\Tquesse\\Tlefthook",
    "h" : "\\Taha",
    "j" : "\\Thyarmen", # at beginning of word
    "H" : "\\Thyarmen\\TTtwodotsbelow",
    "R" : "\\Troomen\\TTdoubler",
    "Q" : "\\Tquesse",
    "d" : "\\Tando",
    "b" : "\\Tumbar",
    "g" : "\\Tanga",
    "G" : "\\Tungwe",
    "<" : "\\Thwesta",
    "ń" : "\\Tanto",
    "ṕ" : "\\Tampa",
    "ć" : "\\Tanca",
    "%" : "\\Tunque",
    "W" : "\\Tnwalme",
    "&" : "\\Tarda",
    "€" : "\\Talda",
    "S" : "\\Tesse",
    "Ś" : "\\Tessenuquerna",
    "=" : "\\Thalla\\Tlambe",
    ">" : "\\Thalla\\Troomen",
    "M" : "\\Tmalta\\TTdoubler",
    "N" : "\\Tnuumen\\TTdoubler",
    "T" : "\\Ttinco\\TTdoubler",
    "C" : "\\Tcalma\\TTdoubler",
    "P" : "\\Tparma\\TTdoubler",
    "L" : "\\Tlambe\\TTdoubler",
    "m̀" : "\\Tmalta\\TTtwodotsbelow",
    "ǹ" : "\\Tnuumen\\TTtwodotsbelow",
    "ŕ" : "\\Troomen\\TTtwodotsbelow",
    "ĺ" : "\\Tlambe\\TTtwodotsbelow",
    "ÿ" : "\\Tcalma\\TTtwodotsbelow",
    "ý" : "\\Tparma\\TTtwodotsbelow",
    "ẅ" : "\\Tcalma\\TTtwodotsbelow",
    "Á" : "\\Tyanta\\TTthreedots",
    "Ó" : "\\Tyanta\\TTrightcurl",
    "Ú" : "\\Tyanta\\TTleftcurl",
    "Ì" : "\\Tuure\\TTdot",
    "È" : "\\Tuure\\TTacute",
    "À" : "\\Tuure\\TTthreedots",
    "a" : "\\TTthreedots",
    "e" : "\\TTacute",
    "i" : "\\TTdot",
    "o" : "\\TTrightcurl",
    "u" : "\\TTleftcurl",
    "é" : "\\TTdoubleacute",
    "ó" : "\\TTdoublerightcurl",
    "ú" : "\\TTdoubleleftcurl",
    "|" : "\\Ttelco",
    "/" : "\\raisebox{-0.7ex}{\\tengmag{1.3}\\rotatebox[origin=c]{-15}{\\Thalla}\\tengmag{1}}",
    "^" : "\\Taara",
    "~" : "\\Trighthook",
    "," : "\\Tcentereddot",
    ":" : "\\Tthreeverticaldots",
    ";" : "\\Tcolon",
    "." : "\\Tcolon\\Tcentereddot",
    "!" : "\\raisebox{-0.5ex}{\\tengmag{1.1}\\Texclamation\\tengmag{1}}",
    "?" : "\\tengmag{1.1}\\Tquestion\\tengmag{1}",
    "(" : "\\raisebox{0.5ex}{\\tengmag{1.1}\\rotatebox[origin=c]{180}{\\Tparenthesis}\\tengmag{1}}",
    ")" : "\\tengmag{1.1}\\Tparenthesis\\tengmag{1}",
    "-" : "\\Tcenteredtilde",
    "0" : "\\Tzero\\TTdecimal",
    "1" : "\\Tone\\TTdecimal",
    "2" : "\\Ttwo\\TTdecimal",
    "3" : "\\Tthree\\TTdecimal",
    "4" : "\\Tfour\\TTdecimal",
    "5" : "\\Tfive\\TTdecimal",
    "6" : "\\Tsix\\TTdecimal",
    "7" : "\\Tseven\\TTdecimal",
    "8" : "\\Teight\\TTdecimal",
    "9" : "\\Tnine\\TTdecimal",
    "Z" : "\\Tzero\\TTduodecimal",
    "µ" : "\\Tone\\TTduodecimal",
    "ẗ" : "\\Ttwo\\TTduodecimal",
    "ĸ" : "\\Tthree\\TTduodecimal",
    "ð" : "\\Tfour\\TTduodecimal",
    "$" : "\\Tfive\\TTduodecimal",
    "ſ" : "\\Tsix\\TTduodecimal",
    "ŧ" : "\\Tseven\\TTduodecimal",
    "ø" : "\\Teight\\TTduodecimal",
    "æ" : "\\Tnine\\TTduodecimal",
    "§" : "\\Tten\\TTduodecimal",
    "þ" : "\\Televen\\TTduodecimal"
}
